name: main
run-name: test [default]

on:
  push:
    branches:
      - main

jobs:
  pull_request:
    uses: ./.github/workflows/cypress.yml
    secrets: inherit
  
  # print_vars:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - name: print variables
  #       run: echo [${{ needs.setup.outputs.myvar }}]
