name: main_flow

on:
  push:
    branches:
      - main

jobs:
  call_setup:
    runs-on: ubuntu-latest
    name: "call first yml"
    uses: wilder-gonzales-webbeds/testproject/.github/workflows/setup.yml@main
  
  test_vars:
    runs-on: ubuntu-latest
    needs: call_setup
    steps:
      - name: "print myvar"
        run: echo [${{ needs.call_setup.outputs.myvar }}]
