name: main
run-name: main_flow [default]

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    uses: ./.github/workflows/cypress.yml
    #name: "setup.yml"
  
  # print_vars:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - name: print variables
  #       run: echo [${{ needs.setup.outputs.myvar }}]
