name: main
run-name: main_flow [default]

on:
  push:
    branches:
      - main

jobs:
  pull_request:
    uses: ./.github/workflows/cypress.yml
    # with:
    #   build-and-verify: ${{needs.EnvSetup.outputs.build-and-verify}}
    secrets:
      CYPRESS_sunhotelsUsername: ${{ secrets.CYPRESS_sunhotelsUsername }}
      CYPRESS_sunhotelsPassword: ${{ secrets.CYPRESS_SUNHOTELSPASSWORD }}
  
  # print_vars:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - name: print variables
  #       run: echo [${{ needs.setup.outputs.myvar }}]
