name: main
run-name: main_flow

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    name: "setup.yml"
  
  print_vars:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: print variables
        run: echo [${{ needs.setup.outputs.myvar }}]
