name: main_flow

on:
  push:
    branches:
      - main

jobs:
  call_setup:
    uses: ./.github/workflows/setup.yml
    name: "call first yml"
  
  test_vars:
    runs-on: ubuntu-latest
    needs: call_setup
    steps:
      - name: "print myvar"
        run: echo [${{ needs.call_setup.outputs.myvar }}]
