name: main
run-name: main_flow [default]

on:
  push:
    branches:
      - main

jobs:
  pull_request:
    uses: ./.github/workflows/cypress.yml
    #name: "setup.yml"
    # with:
    #   # Records to Cypress Cloud 
    #   # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
    #   record: true
    #   command: npm run test:ci
    env:
      # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
      # in GitHub repo → Settings → Secrets → Actions
      # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      # CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      # # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
      # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      # Test user credentials
      CYPRESS_sunhotelsUsername: ${{ jobs.pull_request.outputs.CYPRESS_sunhotelsUsername }}
      CYPRESS_sunhotelsPassword: ${{ jobs.pull_request.outputs.CYPRESS_sunhotelsPassword }}
  
  # print_vars:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - name: print variables
  #       run: echo [${{ needs.setup.outputs.myvar }}]
